# Generated by Django 4.0 on 2021-12-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
