# Generated by Django 4.0 on 2021-12-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf_kayit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_adi', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.DeleteModel(
            name='PdfKaydi',
        ),
    ]
